language: ruby
cache: bundler
before_install:
    - gem install bundler -v '< 2'
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  email: deploy@travis-ci.org
  name: Deployment Bot
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages